import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import '@/app/globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/blocks/home/Navbar';
import RecentTx from '@/components/blocks/home/RecentTx';
import SearchBar from '@/components/blocks/home/Search';

const jetbrains = JetBrains_Mono({
  display: 'swap',
  weight: ['200', '400', '700'],
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',

        'font-mono',
        jetbrains.className,
      )}>
      <body className='min-h-full flex flex-col bg-background'>
        <Navbar />
        <RecentTx />
        <SearchBar />
        {children}
      </body>
    </html>
  );
}
